apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cybernova.fullname" . }}-secret
  labels:
    {{- include "cybernova.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.config.secretKey | default (randAlphaNum 32) | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cybernova.fullname" . }}-db
  labels:
    {{- include "cybernova.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ printf "postgresql+asyncpg://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password .Release.Name .Values.postgresql.auth.database | b64enc | quote }}
