"""
CyberNova — First-Run Setup Flow
GET  /api/v1/setup/status   — Check if any users exist
POST /api/v1/setup/admin    — Create first admin
GET  /api/v1/setup/health   — Environment health check
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone, timedelta

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, field_validator
from sqlalchemy import select, func

from cybernova.database.postgres.models import User, Tenant, OrganizationKey
from cybernova.auth.services.auth_service import auth_service
from cybernova.config.settings import get_settings
from cybernova.core.utils.helpers import generate_org_key, hash_org_key

log = logging.getLogger("cybernova.setup")
router = APIRouter(prefix="/api/v1/setup", tags=["Setup"])


class SetupStatus(BaseModel):
    needs_setup: bool
    admin_exists: bool
    db_connected: bool
    redis_connected: bool


class CreateAdminRequest(BaseModel):
    email: str
    password: str
    company_name: str
    company_size: str = ""
    username: str = "admin"

    @field_validator("password")
    @classmethod
    def validate_password_strength(cls, v: str) -> str:
        import re
        if len(v) < 8:
            raise ValueError("Password must be at least 8 characters long")
        if not re.search(r"[A-Z]", v):
            raise ValueError("Password must contain at least one uppercase letter")
        if not re.search(r"[a-z]", v):
            raise ValueError("Password must contain at least one lowercase letter")
        if not re.search(r"\d", v):
            raise ValueError("Password must contain at least one digit")
        if not re.search(r"[!@#$%^&*(),.?\":{}|<>_\-+]", v):
            raise ValueError("Password must contain at least one special character")
        return v


@router.get("/status", summary="Check if setup is needed")
async def setup_status():
    """Returns whether the system needs first-run setup."""
    db_connected = False
    user_count = 0

    try:
        from cybernova.database.postgres.session import async_session_factory as _factory
        async with _factory() as db:
            result = await db.execute(select(func.count()).select_from(User))
            user_count = result.scalar() or 0
            db_connected = True
    except Exception as e:
        log.warning("Setup status DB check failed (degraded mode): %s", e)

    redis_connected = False
    try:
        from cybernova.database.redis import get_redis
        redis = await get_redis()
        redis_connected = redis is not None
    except Exception:
        pass

    return SetupStatus(
        needs_setup=user_count == 0 and db_connected,
        admin_exists=user_count > 0,
        db_connected=db_connected,
        redis_connected=redis_connected,
    )


@router.post("/admin", summary="Create first admin user")
async def create_admin(payload: CreateAdminRequest):
    """Create the first admin user and tenant. Only works if no users exist.
    Automatically generates an organization key for staff invitations.
    """
    from cybernova.database.postgres.session import async_session_factory as _factory
    async with _factory() as db:
        result = await db.execute(select(func.count()).select_from(User))
        if (result.scalar() or 0) > 0:
            raise HTTPException(status_code=400, detail="Setup already completed")

        # Create tenant with enterprise plan and company info
        tenant = Tenant(name=payload.company_name, plan="enterprise",
                        company_size=payload.company_size, is_active=True)
        db.add(tenant)
        await db.flush()

        # Register admin user
        result = await auth_service.register(
            db, payload.username, payload.email, payload.password,
            tenant_name=payload.company_name, roles=["admin"],
            company_size=payload.company_size,
        )

        # Generate org key for staff invitations (if not already generated by register)
        if not result.org_key:
            org_key_raw = generate_org_key()
            key_hash = hash_org_key(org_key_raw)
            org_key_obj = OrganizationKey(
                tenant_id=tenant.id,
                key_hash=key_hash,
                name="default",
                expires_at=datetime.now(timezone.utc) + timedelta(days=365),
            )
            db.add(org_key_obj)
            await db.flush()
            # Update the result with the generated org_key
            result.org_key = org_key_raw

        await db.commit()

        log.info("First admin created for tenant: %s (org_key: %s...)",
                 payload.company_name, result.org_key[:12] if result.org_key else "none")
        return {
            "success": True,
            "tenant_id": tenant.id,
            "org_key": result.org_key,
            **result.model_dump(exclude={"org_key"}),
        }


@router.get("/health", summary="Environment health check")
async def env_health():
    """Check backend, DB, Redis connectivity."""
    settings = get_settings()
    health = {"backend": True, "db": False, "redis": False, "environment": settings.environment}

    try:
        from cybernova.database.postgres.session import async_session_factory as _factory
        async with _factory() as db:
            await db.execute(__import__("sqlalchemy").text("SELECT 1"))
            health["db"] = True
    except Exception as e:
        log.debug("DB health check failed: %s", e)

    try:
        from cybernova.database.redis import get_redis
        redis = await get_redis()
        if redis:
            await redis.ping()
            health["redis"] = True
    except Exception as e:
        log.debug("Redis health check failed: %s", e)

    return health
