"""
CyberNova — Observability Module
Structured logging, request tracing, performance metrics.
"""
from __future__ import annotations

import time
import logging
from datetime import datetime, timezone
from typing import Any, Dict, Optional

log = logging.getLogger("cybernova.monitoring")


class MetricsCollector:
    """Lightweight in-process metrics collector with Prometheus export."""

    def __init__(self) -> None:
        self._counters: Dict[str, float] = {}
        self._histograms: Dict[str, list] = {}
        self._gauges: Dict[str, float] = {}

    def increment(self, metric: str, value: float = 1.0, tags: Optional[Dict[str, str]] = None) -> None:
        key = self._tagged_key(metric, tags)
        self._counters[key] = self._counters.get(key, 0) + value

    def gauge(self, metric: str, value: float, tags: Optional[Dict[str, str]] = None) -> None:
        key = self._tagged_key(metric, tags)
        self._gauges[key] = value

    def observe(self, metric: str, value: float, tags: Optional[Dict[str, str]] = None) -> None:
        key = self._tagged_key(metric, tags)
        if key not in self._histograms:
            self._histograms[key] = []
        self._histograms[key].append(value)
        if len(self._histograms[key]) > 10000:
            self._histograms[key] = self._histograms[key][-5000:]

    def get_all(self) -> Dict[str, Any]:
        result = {
            "counters": {k: round(v, 2) for k, v in self._counters.items()},
            "gauges": {k: round(v, 2) for k, v in self._gauges.items()},
            "histograms": {},
        }
        for key, values in self._histograms.items():
            if values:
                result["histograms"][key] = {
                    "count": len(values),
                    "avg": round(sum(values) / len(values), 3),
                    "max": round(max(values), 3),
                    "min": round(min(values), 3),
                }
        return result

    def export_prometheus(self) -> str:
        lines = []

        _all_metrics = [
            ("cybernova_events_ingested_total", "counter", "Events ingested into the pipeline"),
            ("cybernova_events_processed_total", "counter", "Events successfully processed"),
            ("cybernova_alerts_generated_total", "counter", "Alerts generated by detection"),
            ("cybernova_processing_latency_ms", "histogram", "Event processing latency"),
            ("cybernova_stream_lag", "gauge", "Current stream lag"),
            ("cybernova_worker_failures_total", "counter", "Worker failure count"),
            ("cybernova_soar_actions_total", "counter", "SOAR actions executed"),
            ("cybernova_soar_action_duration_ms", "histogram", "SOAR action execution duration"),
            ("cybernova_http_requests_total", "counter", "HTTP requests by endpoint"),
            ("cybernova_http_request_duration_ms", "histogram", "HTTP request latency"),
            ("cybernova_incidents_created_total", "counter", "Incidents created"),
            ("cybernova_incidents_resolved_total", "counter", "Incidents resolved"),
            ("cybernova_detection_rule_hits_total", "counter", "Detection rule hit count by rule"),
            ("cybernova_alerts_false_positive_total", "counter", "False positive alert count by rule"),
            ("cybernova_events_by_tenant_total", "counter", "Events processed by tenant"),
            ("cybernova_pipeline_stage_latency_ms", "histogram", "Per-stage pipeline processing latency"),
            ("cybernova_stage_slo_success_rate", "gauge", "Per-stage SLO success rate (0-100)"),
            ("cybernova_stage_slo_p99_latency_ms", "gauge", "Per-stage SLO P99 latency"),
            ("cybernova_stage_slo_throughput_per_min", "gauge", "Per-stage SLO throughput"),
            ("cybernova_pipeline_running", "gauge", "Pipeline orchestrator status"),
            ("cybernova_enrichment_running", "gauge", "Enrichment worker health"),
            ("cybernova_correlation_running", "gauge", "Correlation worker health"),
            ("cybernova_ai_worker_running", "gauge", "AI investigation worker health"),
            ("cybernova_circuit_breaker_status", "gauge", "Circuit breaker state 0=closed 1=open 2=half-open"),
            ("cybernova_dlq_depth", "gauge", "Dead letter queue depth"),
            ("cybernova_events_failed_total", "counter", "Failed event count"),
            ("cybernova_blocked_ips_total", "counter", "Blocked IPs count"),
            ("cybernova_devices_isolated_total", "gauge", "Devices in isolated state"),
            ("cybernova_users_disabled_total", "counter", "Users disabled by SOAR"),
            ("cybernova_suricata_alerts_total", "counter", "Suricata IDS/IPS alert count"),
            ("cybernova_alerts_critical_total", "counter", "Critical severity alerts"),
            ("cybernova_alerts_high_total", "counter", "High severity alerts"),
            ("cybernova_alerts_medium_total", "counter", "Medium severity alerts"),
            ("cybernova_alerts_low_total", "counter", "Low severity alerts"),
            ("cybernova_mitre_tactic_active", "gauge", "Active MITRE ATT&CK tactics"),
        ]
        for metric, mtype, desc in _all_metrics:
            lines.append(f"# HELP {metric} {desc}")
            lines.append(f"# TYPE {metric} {mtype}")

        for key, value in self._counters.items():
            name, labels = self._split_key(key)
            lines.append(f"cybernova_{name}{labels} {value}")

        for key, value in self._gauges.items():
            name, labels = self._split_key(key)
            lines.append(f"cybernova_{name}{labels} {value}")

        _latency_buckets = [1, 5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000, 10000]
        for key, values in self._histograms.items():
            if not values:
                continue
            name, labels = self._split_key(key)
            count = len(values)
            total = sum(values)
            for le in _latency_buckets:
                bucket_count = sum(1 for v in values if v <= le)
                if labels:
                    label_content = labels[1:-1]  # strip { and }
                    lines.append(f"cybernova_{name}_bucket{{{label_content},le=\"{le}\"}} {bucket_count}")
                else:
                    lines.append(f"cybernova_{name}_bucket{{le=\"{le}\"}} {bucket_count}")
            if labels:
                label_content = labels[1:-1]
                lines.append(f"cybernova_{name}_bucket{{{label_content},le=\"+Inf\"}} {count}")
            else:
                lines.append(f"cybernova_{name}_bucket{{le=\"+Inf\"}} {count}")
            lines.append(f"cybernova_{name}_count{labels} {count}")
            lines.append(f"cybernova_{name}_sum{labels} {total}")

        self._export_slo_metrics(lines)
        self._export_pipeline_metrics(lines)

        return "\n".join(lines) + "\n"

    @staticmethod
    def _split_key(key: str):
        if "{" in key and key.endswith("}"):
            name, rest = key.split("{", 1)
            return name, "{" + rest
        return key, ""

    def _export_slo_metrics(self, lines: list) -> None:
        try:
            from cybernova.monitoring.slo import slo_engine
            report = slo_engine.report()
            for stage, snap in report.get("stages", {}).items():
                tag = f'{{stage="{stage}"}}'
                lines.append(f"cybernova_stage_slo_success_rate{tag} {snap.get('success_rate_pct', 0)}")
                lines.append(f"cybernova_stage_slo_p99_latency_ms{tag} {snap.get('p99_latency_ms', 0)}")
                lines.append(f"cybernova_stage_slo_throughput_per_min{tag} {snap.get('throughput_per_min', 0)}")
        except Exception as exc:
            log.debug("SLO metrics export skipped: %s", exc)

    def _export_pipeline_metrics(self, lines: list) -> None:
        try:
            from cybernova.pipeline.unified_pipeline import unified_pipeline
            pm = unified_pipeline._metrics
            if pm["ingested"] > 0:
                lines.append(f"cybernova_events_ingested_total {pm['ingested']}")
            processed = pm["normalized"] + pm["enriched"]
            if processed > 0:
                lines.append(f"cybernova_events_processed_total {processed}")
            if pm["alerted"] > 0:
                lines.append(f"cybernova_alerts_generated_total {pm['alerted']}")
            if pm["errors"] > 0:
                lines.append(f"cybernova_events_failed_total {pm['errors']}")
            if pm["latency_ms"]:
                lines.append(f"cybernova_processing_latency_ms_sum {sum(pm['latency_ms'])}")
                lines.append(f"cybernova_processing_latency_ms_count {len(pm['latency_ms'])}")
            lines.append(f"cybernova_pipeline_running {1 if unified_pipeline._running else 0}")
        except Exception as exc:
            log.debug("Pipeline metrics export skipped: %s", exc)

    def reset(self) -> None:
        self._counters.clear()
        self._histograms.clear()
        self._gauges.clear()

    @staticmethod
    def _tagged_key(metric: str, tags: Optional[Dict[str, str]]) -> str:
        if not tags:
            return metric
        tag_str = ",".join(f'{k}="{v}"' for k, v in sorted(tags.items()))
        return f"{metric}{{{tag_str}}}"


class TracingContext:
    """Simple request tracing context."""

    def __init__(self, trace_id: str, operation: str) -> None:
        self.trace_id = trace_id
        self.operation = operation
        self.start_time = time.perf_counter()
        self.spans: list = []

    def add_span(self, name: str, duration_ms: float) -> None:
        self.spans.append({"name": name, "duration_ms": round(duration_ms, 2)})

    def finish(self) -> Dict[str, Any]:
        elapsed = (time.perf_counter() - self.start_time) * 1000
        return {
            "trace_id": self.trace_id, "operation": self.operation,
            "total_ms": round(elapsed, 2), "spans": self.spans,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }


metrics = MetricsCollector()


# --- Simple metrics tracking for pipeline ---
_pipeline_metrics = {
    "ingestion_total": 0,
    "ingestion_deduped": 0,
    "ingestion_failed": 0,
    "correlation_triggers": 0,
    "risk_escalations": 0,
    "risk_confirmations": 0,
    "soar_triggered": 0,
    "soar_blocked": 0,
}


def track_ingestion(ingested=True, deduped=False, failed=False):
    """Track ingestion events."""
    if ingested:
        _pipeline_metrics["ingestion_total"] += 1
    if deduped:
        _pipeline_metrics["ingestion_deduped"] += 1
    if failed:
        _pipeline_metrics["ingestion_failed"] += 1


def track_correlation():
    """Track correlation triggers."""
    _pipeline_metrics["correlation_triggers"] += 1


def track_risk(escalated=False, confirmed=False):
    """Track risk events."""
    if escalated:
        _pipeline_metrics["risk_escalations"] += 1
    if confirmed:
        _pipeline_metrics["risk_confirmations"] += 1


def track_soar(triggered=False):
    """Track SOAR events."""
    if triggered:
        _pipeline_metrics["soar_triggered"] += 1
    else:
        _pipeline_metrics["soar_blocked"] += 1


def get_pipeline_metrics():
    """Get pipeline metrics."""
    return {
        "ingestion": {
            "total": _pipeline_metrics["ingestion_total"],
            "deduped": _pipeline_metrics["ingestion_deduped"],
            "failed": _pipeline_metrics["ingestion_failed"],
        },
        "correlation": {
            "triggers": _pipeline_metrics["correlation_triggers"],
        },
        "risk": {
            "escalations": _pipeline_metrics["risk_escalations"],
            "confirmations": _pipeline_metrics["risk_confirmations"],
        },
        "soar": {
            "triggered": _pipeline_metrics["soar_triggered"],
            "blocked": _pipeline_metrics["soar_blocked"],
        },
    }
